# Generated by Django 5.1.7 on 2025-04-14 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0003_rename_summ_contract_cost_and_more"),
        ("leads", "0002_remove_lead_user_lead_email_lead_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_client",
                        to="contracts.contract",
                        verbose_name="Контракт",
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_client",
                        to="leads.lead",
                        verbose_name="Потенциальный клиент",
                    ),
                ),
            ],
        ),
    ]
