# Generated by Django 5.1.7 on 2025-04-16 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_contract_is_signed"),
        ("customers", "0001_initial"),
        ("leads", "0003_lead_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="contract",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="contracts.contract",
                verbose_name="Контракт",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="lead",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="leads.lead",
                verbose_name="Потенциальный клиент",
            ),
        ),
    ]
