# Generated by Django 5.1.7 on 2025-04-11 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="user",
        ),
        migrations.AddField(
            model_name="lead",
            name="email",
            field=models.EmailField(default="", max_length=254, verbose_name="Email"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="first_name",
            field=models.CharField(default="", max_length=100, verbose_name="Имя"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="last_name",
            field=models.CharField(default="", max_length=100, verbose_name="Фамилия"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lead",
            name="ad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ads.ads",
                verbose_name="Рекламная компания",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(
                max_length=15, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
