# Generated by Django 5.1.7 on 2025-04-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_remove_lead_user_lead_email_lead_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Является ли клиент активным"
            ),
        ),
    ]
