# Generated by Django 5.1.7 on 2025-04-11 11:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_alter_product_description_alter_product_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "document",
                    models.FileField(
                        upload_to="contracts/documents/",
                        verbose_name="Файл с документом",
                    ),
                ),
                (
                    "signed_at",
                    models.DateField(
                        default=datetime.datetime(
                            2025,
                            4,
                            11,
                            11,
                            49,
                            55,
                            633038,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="Дата заключения контракта",
                    ),
                ),
                ("valid_until", models.DateField(verbose_name="Контракт действует до")),
                (
                    "summ",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма (в руб)"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Предоставляемая услуга",
                    ),
                ),
            ],
        ),
    ]
