# Generated by Django 5.1.7 on 2025-04-11 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="signed_at",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Дата заключения контракта",
            ),
        ),
    ]
