# Generated by Django 5.1.7 on 2025-04-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_alter_contract_signed_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="summ",
            new_name="cost",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="valid_until",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="signed_at",
            new_name="start_date",
        ),
    ]
