# Generated by Django 5.1.7 on 2025-04-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_rename_summ_contract_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="is_signed",
            field=models.BooleanField(
                default=False, verbose_name="Является ли контракт подписанным"
            ),
        ),
    ]
